### ISSUE TITLE
Wrong Token and Data Returned

### ISSUE THREAD

**Issue by asadamatic** [usefulteam/jwt-auth#127] opened 2024-08-01 05:32 UTC
Hi there, I'm facing a pretty weird issue with the `/token` request. That is, no matter what credentials I pass ( even invalid ), I get the data of a particular user and when I use that token for the `/users/me` request, it returns the data for that particular user.

**Comment by dominic-ks** [comment] 2024-08-01 09:02
@asadamatic are you using any REST caching plugins?

**Comment by pinoceniccola** [comment] 2024-08-02 12:37
The same thing happened to me and it returned a valid token even with no `username` and/or `password` parameters. It was kind of scary at first.

It turns out that you (or your app) are probably carrying on the `refresh_token` cookie in your request header from a previous response and in the current logic it takes precedence over `username` and `password` parameters.

This is basically another side effect of the same issue found in #128.

So, it would be a good idea if for the `/token` endpoint the `refresh_token` cookie is ignored. Or, at least, users should be warned of the current logic in the docs. There are many apps and frameworks that silently pass cookies over requests, it's not always easy to catch issues like these.

**Comment by asadamatic** [comment] 2024-08-03 05:03
@dominic-ks I'm not using any such plugin. For now, I switched to the [JWT Authentication](https://en-ca.wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) and it seems to be working fine.

@pinoceniccola I checked the Rest API logs and it does contain the `refresh_token` in the cookie header.

**Comment by dominic-ks** [comment] 2024-08-03 17:20
OK, so do we think this is the same issue as [#128](https://github.com/usefulteam/jwt-auth/issues/128)?

**Comment by asadamatic** [comment] 2024-08-10 06:34
@dominic-ks Yes, it seems so

**Comment by pinoceniccola** [comment] 2024-09-02 16:45
> OK, so do we think this is the same issue as [#128](https://github.com/usefulteam/jwt-auth/issues/128)?

@dominic-ks definitely. Only difference is if the `refresh_token` cookie is still valid (this issue) or not (#128).

The problem lies in these lines: 
https://github.com/usefulteam/jwt-auth/blob/f99ca5a99805d006785396031049dd3c06dd59d7/class-auth.php#L181-L192

Where the `refresh_token` cookie always takes precedence over `username` / `password` params. This logic seems very counterintuitive, should be at least explained in the docs.

**Comment by dominic-ks** [comment] 2024-09-06 15:59
@sun do you agreed that logic should be switched for this? If so, I'll have a look at that. Only thought is if people have apps that are currently relying on the refresh cookie taking priority over login details, but I can't imagine why they would be....

**Comment by sun** [comment] 2024-09-06 17:37
Having username/password take precedence in case a refresh token is also passed is fine.  If a client is passing both then we can safely assume that the intention was to log in with user credentials.  We can change that. 👍

What I don’t understand is why the client would prompt the user to log in manually with credentials of the client still has a refresh token cookie. Normally I’d expect a client with refresh token to first try that and if it is rejected the refresh token should be deleted before the client reauthenticates. But I guess there can be edge case scenarios in which that is not as clean as in theory. Sorry for not thinking of such possibilities.

**Comment by dominic-ks** [comment] 2024-09-10 16:27
Yeah I think the problem is that in this case the browser is retaining the refresh token itself, so perhaps app logic says user is logged out, e.g. deleted any stored tokens from local storage, but then when logging in again the browser is still sending the cookie. Could be wrong, anyway, [PR created](https://github.com/usefulteam/jwt-auth/pull/130).

**Comment by robbsnell** [comment] 2024-10-02 07:19
I notice that PR has been accepted. 
Is there a plan to release an update with this fix, because the current behaviour is odd.

**Comment by sun** [comment] 2024-10-02 07:58
The PR has been merged and will be part of the next release. 🙂

**Closed by sun** 2024-10-02 07:58 UTC

**Comment by robbsnell** [comment] 2024-10-22 03:48
So is there a plan to actually create an update for the plugin?
It hasn't been updated in over 6 months.
I mean merging code is great but ultimately useless if we have to go and hack the plugin ourselves to get anything working.
