### ISSUE TITLE
Missing required file - fatal error -> version 2.1.2

### ISSUE THREAD

**Issue by adambichler** [usefulteam/jwt-auth#81] opened 2022-11-07 21:33 UTC
When updating from version 2.1.0 to version 2.1.2, a fatal erreor occurs on my website. This ist the error i get: 

`An error of type E_COMPILE_ERROR was caused on line 25 of the path-to-my-root-direcotry/wp-content/plugins/jwt-auth/vendor/composer/autoload_real.php file. Error message: require(): Failed opening required 'path-to-my-root-direcotry/wp-content/plugins/jwt-auth/vendor/composer/platform_check.php' (include_path='.:/ usr/local/php74/pear')`

I checked the wordpress repository plugin ZIP and the "platform_check.php" file is indeed missing in the vendor/composer/ folder.
When downgrading to version 2.1.0, everything is working fine again.

Thanks for looking into it!

**Comment by dominic-ks** [comment] 2022-11-07 22:26
Just closing as a duplicate of https://github.com/usefulteam/jwt-auth/issues/80 as you've seen.

**Closed by dominic-ks** 2022-11-07 22:26 UTC
