### ISSUE TITLE
Response is always HTTP status code 200

### ISSUE THREAD

**Issue by Zyles** [usefulteam/jwt-auth#5] opened 2020-08-06 20:19 UTC
Every response, even with an error it uses the status code 200, which is incorrect by rest standards.

Should return the correct status code on errors.

**Comment by contactjavas** [comment] 2020-08-06 22:51
Hi @Zyles , thanks for reporting.
I will check it and get back to here

**Comment by contactjavas** [comment] 2020-08-06 22:58
I haven't checked it yet, but the error responses should be 403 [as described here](https://github.com/usefulteam/jwt-auth#error-responses). 

Is it the error responses you're referring to @Zyles ?

**Comment by Zyles** [comment] 2020-08-06 23:23
HTTP status code does not follow REST.

![image](https://user-images.githubusercontent.com/1741593/89592303-8e9d2980-d84c-11ea-88bf-c9e0e09d1250.png)

**Comment by morksinaanab** [comment] 2020-09-24 15:37
@contactjavas  Mohon Maaf, 

I think you can solve this by passing a second parameter to WP_REST_Response with the value of 403, wherever in your code you return this object with statusCode 403. I tried it locally in my install of your plugin and it seems to work

trims.

![Uploading image.png…]()

**Comment by contactjavas** [comment] 2020-09-24 22:00
Hi @morksinaanab, terimakasih banyak :-) atas sarannya.

They're already implemented & pushed to master. But I can't push it yet to Wp plugin svn.

Those errors now have real 403 http status except `jwt_auth_no_auth_header` and `jwt_bad_auth_header`. There's problem when I assigned http status 403 to those two.

Btw your Indonesian language is great :)

Terimakasih!

**Comment by morksinaanab** [comment] 2020-09-25 06:07
After living for 9 years in Indonesia, I hope to know the language a little bit :-) Terimakasih buat fix2nya!

**Comment by BeSquares** [comment] 2020-10-02 03:21
#13

**Comment by cedricDevWP** [comment] 2020-11-06 20:42
The update with this correction will be available soon ?

**Comment by kosso** [comment] 2020-11-11 00:56
@cedricDevWP The `class-auth.php` file has been updated here on github. But it appears to still be old on the Wordpress Plugins Directory when installing via Wordpress. 

I just manually replaced the installed file with the one from here. 

Now I get the expected HTTP Response status codes. 👍🏼

**Comment by contactjavas** [comment] 2020-12-17 02:24
Hi Guys, I expect to push minor update to the plugin this week (including the fix for this).

**Comment by omarkhatibco** [comment] 2021-01-18 16:25
Hi @contactjavas, 

did you push the update, or not yet ?

**Comment by sun** [comment] 2021-07-07 10:57
The problem is fixed in the code on GitHub, but it seems like no new release version of the [jwt-auth plugin](https://wordpress.org/plugins/jwt-auth/) has been published yet on wordpress.org:
![image](https://user-images.githubusercontent.com/41992/124747406-2ce4b400-df22-11eb-8620-ae8343fbd760.png)

It would be good if the GitHub repository would also contain the release tags. There are [no tags](https://github.com/usefulteam/jwt-auth/tags) currently. That will allow users and contributors to identify more quickly which changes are part of which release version.

**Comment by contactjavas** [comment] 2021-08-06 02:59
Hey friends.. sorry for the long wait. I've been focusing on my daily work.
Version 2.0.0 has just been released on GitHub and in the WordPress plugins repository. It includes a fix for this issue.

Let me close this issue. Please let me know if you encounter any issues regarding the release.
Thanks

**Closed by contactjavas** 2021-08-06 02:59 UTC
